CREATE DATABASE [RadioBroadcasts];



CREATE TABLE [dbo].[TBL_ADMIN](
	    [TblAdminId] INT IDENTITY(1,1) NOT NULL,
		[Code] NVARCHAR(3) NULL,
		[AdminName] NVARCHAR(100) NULL,

		CONSTRAINT PK_TBL_ADMIN PRIMARY KEY CLUSTERED ([TblAdminId])
);

CREATE TABLE [dbo].[TBL_ANT](
	    [TblAntId] INT IDENTITY(1,1) NOT NULL,
		[Code] INT NULL,
		[Ant] NVARCHAR(75) NULL,

		CONSTRAINT PK_TBL_ANT PRIMARY KEY CLUSTERED ([TblAntId])
);

CREATE TABLE [dbo].[TBL_BROADCASTER](
	    [TblBroadcasterId] INT IDENTITY(1,1) NOT NULL,
		[Code] NVARCHAR(3) NULL,
		[Broadcaster] NVARCHAR(140) NULL,

		CONSTRAINT PK_TBL_BROADCASTER PRIMARY KEY CLUSTERED ([TblBroadcasterId])
);

CREATE TABLE [dbo].[TBL_HF_SCHEDULE](
	    [TblHfScheduleId] INT IDENTITY(1,1) NOT NULL,
		[Freq] INT NULL,
		[Start] INT NULL,
		[Stop] INT NULL,
		[CirafZones] NVARCHAR(100) NULL,
		[LocCode] NVARCHAR(10) NULL,
		[Powr] INT NULL,
		[AziMuth] INT NULL,
		[Slew] INT NULL,
		[AntCode] INT NULL,
		[Days] BIGINT NULL,
		[Sdate] NVARCHAR(25) NULL,
		[Edate] NVARCHAR(25) NULL,
		[Mod] NVARCHAR(3) NULL,
		[Afrq] BIGINT NULL,
		[LanguageCode] NVARCHAR(10) NULL,
		[AdminCode] NVARCHAR(3) NULL,
		[BroadcasterCode] NVARCHAR(3) NULL,
		[FmoCode] NVARCHAR(3) NULL,

		CONSTRAINT PK_TBL_HF_SCHEDULE PRIMARY KEY CLUSTERED ([TblHfScheduleId])
);

CREATE TABLE [dbo].[TBL_LANGUAGE](
	    [TblLanguageId] INT IDENTITY(1,1) NOT NULL,
		[Code] NVARCHAR(3) NULL,
		[Language] NVARCHAR(75) NULL,

		CONSTRAINT PK_TBL_LANGUAGE PRIMARY KEY CLUSTERED ([TblLanguageId])
);

CREATE TABLE [dbo].[TBL_LOCATION](
	    [TblLocationId] INT IDENTITY(1,1) NOT NULL,
		[Code] NVARCHAR(3) NULL,
		[Site] NVARCHAR(75) NULL,
		[Adm] NVARCHAR(3) NULL,
		[Lat] NVARCHAR(50) NULL,
		[Long] NVARCHAR(50) NULL,

		CONSTRAINT PK_TBL_LOCATION PRIMARY KEY CLUSTERED ([TblLocationId])
);

