USE [master]
GO
/****** Object:  Database [RadioBroadcasts]    Script Date: 2/11/2024 10:41:37 AM ******/
CREATE DATABASE [RadioBroadcasts]
GO
ALTER DATABASE [RadioBroadcasts] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RadioBroadcasts].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RadioBroadcasts] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET ARITHABORT OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RadioBroadcasts] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RadioBroadcasts] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET  ENABLE_BROKER 
GO
ALTER DATABASE [RadioBroadcasts] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RadioBroadcasts] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET RECOVERY FULL 
GO
ALTER DATABASE [RadioBroadcasts] SET  MULTI_USER 
GO
ALTER DATABASE [RadioBroadcasts] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RadioBroadcasts] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RadioBroadcasts] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RadioBroadcasts] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RadioBroadcasts] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RadioBroadcasts] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'RadioBroadcasts', N'ON'
GO
ALTER DATABASE [RadioBroadcasts] SET QUERY_STORE = ON
GO
ALTER DATABASE [RadioBroadcasts] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [RadioBroadcasts]
GO
/****** Object:  Table [dbo].[TBL_ADMIN]    Script Date: 2/11/2024 10:41:37 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_ADMIN](
	[TblAdminId] [int] IDENTITY(1,1) NOT NULL,
	[Code] [nvarchar](3) NULL,
	[AdminName] [nvarchar](100) NULL,
 CONSTRAINT [PK_TBL_ADMIN] PRIMARY KEY CLUSTERED 
(
	[TblAdminId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_ANT]    Script Date: 2/11/2024 10:41:37 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_ANT](
	[TblAntId] [int] IDENTITY(1,1) NOT NULL,
	[Code] [int] NULL,
	[Ant] [nvarchar](75) NULL,
 CONSTRAINT [PK_TBL_ANT] PRIMARY KEY CLUSTERED 
(
	[TblAntId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_BROADCASTER]    Script Date: 2/11/2024 10:41:37 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_BROADCASTER](
	[TblBroadcasterId] [int] IDENTITY(1,1) NOT NULL,
	[Code] [nvarchar](3) NULL,
	[Broadcaster] [nvarchar](140) NULL,
 CONSTRAINT [PK_TBL_BROADCASTER] PRIMARY KEY CLUSTERED 
(
	[TblBroadcasterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_HF_SCHEDULE]    Script Date: 2/11/2024 10:41:37 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_HF_SCHEDULE](
	[TblHfScheduleId] [int] IDENTITY(1,1) NOT NULL,
	[Freq] [int] NULL,
	[Start] [int] NULL,
	[Stop] [int] NULL,
	[CirafZones] [nvarchar](100) NULL,
	[LocCode] [nvarchar](10) NULL,
	[Powr] [int] NULL,
	[AziMuth] [int] NULL,
	[Slew] [int] NULL,
	[AntCode] [int] NULL,
	[Days] [bigint] NULL,
	[Sdate] [nvarchar](25) NULL,
	[Edate] [nvarchar](25) NULL,
	[Mod] [nvarchar](3) NULL,
	[Afrq] [bigint] NULL,
	[LanguageCode] [nvarchar](10) NULL,
	[AdminCode] [nvarchar](3) NULL,
	[BroadcasterCode] [nvarchar](3) NULL,
	[FmoCode] [nvarchar](3) NULL,
 CONSTRAINT [PK_TBL_HF_SCHEDULE] PRIMARY KEY CLUSTERED 
(
	[TblHfScheduleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_LANGUAGE]    Script Date: 2/11/2024 10:41:37 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_LANGUAGE](
	[TblLanguageId] [int] IDENTITY(1,1) NOT NULL,
	[Code] [nvarchar](3) NULL,
	[Language] [nvarchar](75) NULL,
 CONSTRAINT [PK_TBL_LANGUAGE] PRIMARY KEY CLUSTERED 
(
	[TblLanguageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_LOCATION]    Script Date: 2/11/2024 10:41:37 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_LOCATION](
	[TblLocationId] [int] IDENTITY(1,1) NOT NULL,
	[Code] [nvarchar](3) NULL,
	[Site] [nvarchar](75) NULL,
	[Adm] [nvarchar](3) NULL,
	[Lat] [nvarchar](50) NULL,
	[Long] [nvarchar](50) NULL,
 CONSTRAINT [PK_TBL_LOCATION] PRIMARY KEY CLUSTERED 
(
	[TblLocationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[TablesCleanUp]    Script Date: 2/11/2024 10:41:37 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[TablesCleanUp]
AS
BEGIN

TRUNCATE TABLE [RadioBroadcasts].[dbo].[TBL_ADMIN];
DBCC CHECKIDENT (TBL_ADMIN, RESEED, 1);

TRUNCATE TABLE [RadioBroadcasts].[dbo].[TBL_ANT];
DBCC CHECKIDENT ([TBL_ANT], RESEED, 1);

TRUNCATE TABLE [RadioBroadcasts].[dbo].[TBL_BROADCASTER];
DBCC CHECKIDENT ([TBL_BROADCASTER], RESEED, 1);

TRUNCATE TABLE [RadioBroadcasts].[dbo].[TBL_HF_SCHEDULE];
DBCC CHECKIDENT ([TBL_HF_SCHEDULE], RESEED, 1);

TRUNCATE TABLE [RadioBroadcasts].[dbo].[TBL_LANGUAGE];
DBCC CHECKIDENT ([TBL_LANGUAGE], RESEED, 1)

TRUNCATE TABLE [RadioBroadcasts].[dbo].[TBL_LOCATION];
DBCC CHECKIDENT ([TBL_LOCATION], RESEED, 1);

END
GO
USE [master]
GO
ALTER DATABASE [RadioBroadcasts] SET  READ_WRITE 
GO
