USE [RadioBroadcasts];


SELECT * FROM [dbo].[TBL_ADMIN];

SELECT * FROM [dbo].[TBL_ANT];

SELECT * FROM [dbo].[TBL_BROADCASTER];

SELECT * FROM [dbo].[TBL_HF_SCHEDULE];

SELECT * FROM [dbo].[TBL_LANGUAGE];

SELECT * FROM [dbo].[TBL_LOCATION];